server:
  port: 8811
# mysql数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

#mybatis相关配置
mybatis:
  typeAliasesPackage: com.nexwise.entity
  mapper-locations: classpath:mapper/*.xml
#打印sql
logging:
  level:
    com.opencode.dao: debug
  file: F:\log\spring.log
