spring:
  profiles:
    #配置文件选择
    active: dev
  #thymeleaf模板引擎配置
  thymeleaf:
    #是否开启缓存
    cache: false
    #前缀
    prefix: classpath:/templates/
    #后缀
    suffix: .html
    #编码
    encoding: UTF-8

fileupload: E:\fileTest\
