server:
  port: 8082
  session-timeout: 1800
#dev开发环境配置，pro生产环境配置
spring:
  #配置环境选择
  profiles:
    #开发环境
    active: dev
  #thymeleaf模板引擎配置
  thymeleaf:
    #是否开启缓存
    cache: false
    #前缀
    prefix: classpath:/templates/
    #后缀
    suffix: .html
    #编码
    encoding: UTF-8
#mybatis相关配置
mybatis:
  typeAliasesPackage: com.nexwise.entity
  mapper-locations: classpath:mapper/*.xml
#打印sql
logging:
  level:
    com.nexwise.dao: debug