server:
  port: 8081
  session-timeout: 1800
#dev开发环境配置，pro生产环境配置
spring:
  profiles:
    active: dev
#mybatis相关配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.nexwise.entity
  mapper-locations: classpath:/mapper/*.xml